using System;
using System.IO;
using System.Text.Json;
using System.Threading.Tasks;

namespace SheetMusicViewer.Desktop;

/// <summary>
/// Helper class to create sample data for first-time users.
/// Uses the bundled GettingStarted.pdf from Assets/SampleMusic so users can try the app
/// without needing their own PDF collection.
/// </summary>
public static class SampleDataHelper
{
    private const string SampleFolderName = "SampleMusic";
    private const string GettingStartedPdfName = "GettingStarted.pdf";
    
    /// <summary>
    /// Gets the path to the sample music folder in the user's local app data.
    /// </summary>
    public static string GetSampleMusicFolder()
    {
        var appDataFolder = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        return Path.Combine(appDataFolder, "SheetMusicViewer", SampleFolderName);
    }
    
    /// <summary>
    /// Gets the path to the bundled sample music in the app's installation directory.
    /// </summary>
    public static string GetBundledSampleMusicFolder()
    {
        var appDir = AppContext.BaseDirectory;
        return Path.Combine(appDir, "Assets", SampleFolderName);
    }
    
    /// <summary>
    /// Gets the path to the bundled GettingStarted.pdf, if it exists.
    /// Returns null if not found.
    /// </summary>
    public static string? GetBundledGettingStartedPdfPath()
    {
        var bundledFolder = GetBundledSampleMusicFolder();
        var pdfPath = Path.Combine(bundledFolder, GettingStartedPdfName);
        return File.Exists(pdfPath) ? pdfPath : null;
    }
    
    /// <summary>
    /// Ensures sample data exists and returns the path to the sample folder.
    /// If bundled samples exist in Assets, copies them to user's local app data.
    /// </summary>
    public static async Task<string> EnsureSampleDataExistsAsync()
    {
        var sampleFolder = GetSampleMusicFolder();
        
        // Create folder if needed
        if (!Directory.Exists(sampleFolder))
        {
            Directory.CreateDirectory(sampleFolder);
        }
        
        // Check if we already have PDFs in the user's sample folder
        if (Directory.GetFiles(sampleFolder, "*.pdf").Length > 0)
        {
            return sampleFolder;
        }
        
        // Check if bundled samples exist in the app's Assets directory
        var bundledFolder = GetBundledSampleMusicFolder();
        if (Directory.Exists(bundledFolder))
        {
            var bundledFiles = Directory.GetFiles(bundledFolder);
            if (bundledFiles.Length > 0)
            {
                // Copy all bundled samples to user's folder (so they can be modified)
                foreach (var file in bundledFiles)
                {
                    var fileName = Path.GetFileName(file);
                    var destPath = Path.Combine(sampleFolder, fileName);
                    if (!File.Exists(destPath))
                    {
                        File.Copy(file, destPath);
                    }
                }
                return sampleFolder;
            }
        }
        
        // No bundled samples found - return the empty folder
        // The GettingStarted.pdf should be generated by running the manual test:
        // AvaloniaTests.Tests.SamplePdfGeneratorTests.GenerateGettingStartedPdf
        return sampleFolder;
    }
    
    /// <summary>
    /// Checks if sample data is available (either in user folder or bundled).
    /// </summary>
    public static bool HasSampleData()
    {
        var userFolder = GetSampleMusicFolder();
        if (Directory.Exists(userFolder) && Directory.GetFiles(userFolder, "*.pdf").Length > 0)
        {
            return true;
        }
        
        var bundledFolder = GetBundledSampleMusicFolder();
        return Directory.Exists(bundledFolder) && Directory.GetFiles(bundledFolder, "*.pdf").Length > 0;
    }
}
